[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Mostafa", email = "mostafamibrahim12@gmail.com"}]
dynamic = ["version", "description"]
